#!/bin/bash

PROJECT=$(git rev-parse --show-toplevel)
MUTATION=${PROJECT}/mutation-targets
DETECTOR=${PROJECT}/detectors
SCRIPT=${PROJECT}/scripts

git submodule init && git submodule update --recursive

cd ${MUTATION}/grep
git checkout -b tags/v3.4

if [ ! -d ${SCRIPT}/venv ];
then
    virtualenv -p /usr/bin/python3 ${SCRIPT}/venv ;
    source ${SCRIPT}/venv/bin/activate ;
    pip install -r ${SCRIPT}/install.txt
fi
